version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "octotask/maintainers"
    labels:
      - "dependencies"
      - "Status: Triage"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    ignore: []
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 5
    reviewers:
      - "octotask/maintainers"
    labels:
      - "dependencies"
      - "Status: Triage"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
